sudo: required
language: go
go:
  - 1.7.5
  - 1.8

notifications:
    email:
        recipients: dean.karn@gmail.com
        on_success: change
        on_failure: always

install:
    - go get
    - go get -u golang.org/x/tools/cmd/cover
    - go get -u github.com/mattn/goveralls
    - go get -u github.com/go-playground/overalls

script:
    - go test ./...
    - go test -race

after_success:
  - overalls -project="github.com/go-experimental/strutil" -covermode=count -ignore=.git,examples,.semaphore-cache -debug
  - goveralls -coverprofile=overalls.coverprofile -service semaphore -repotoken $COVERALLS_TOKEN